DROP TABLE IF EXISTS heroes CASCADE;
DROP TABLE IF EXISTS monsters CASCADE;
DROP TABLE IF EXISTS battle_statistics CASCADE;

CREATE TABLE IF NOT EXISTS heroes(
id BIGSERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
attack INTEGER NOT NULL,
defense INTEGER NOT NULL,
health INTEGER NOT NULL,
original_health INTEGER NOT NULL,
low_damage INTEGER NOT NULL,
high_damage INTEGER NOT NULL,
recovery INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS monsters(
id BIGSERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
attack INTEGER NOT NULL,
defense INTEGER NOT NULL,
health INTEGER NOT NULL,
low_damage INTEGER NOT NULL,
high_damage INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS battle_statistics(
id BIGSERIAL PRIMARY KEY,
hero BIGINT REFERENCES heroes(id),
monster BIGINT REFERENCES monsters(id),
result BOOLEAN NOT NULL
);